title: Welcome to my blog
author: Kcode90 User
email: koliv@live.com
description: I’m a beginner website developer.
# social links
github_username:  https://github.com/Kcode90

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
